name = "list-ops"
version = "0.1.0"
defaultTargets = ["ListOpsTest"]
testDriver = "ListOpsTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "ListOps"

[[lean_exe]]
name = "ListOpsTest"
root = "ListOpsTest"
