name = "mountain-hike"
version = "0.1.0"
defaultTargets = ["MountainHikeTest"]
testDriver = "MountainHikeTest"
moreLeanArgs = [ "-DwarningAsError=true" ]

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "MountainHike"

[[lean_lib]]
name = "Extra"

[[lean_exe]]
name = "MountainHikeTest"
root = "MountainHikeTest"
